server:
  port: 8080

# canal配置,默认单例
canal:
  host: 127.0.0.1
  port: 11111
  destination: example
  username: canal
  password: canal
  acknowledge-mode: true

elasticsearch:
  host: 127.0.0.1
  port: 9200


